# Generated by Django 4.2.20 on 2025-04-29 08:54

from django.db import migrations, models
import langcorrect.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_uuid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', langcorrect.users.models.ActiveUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
