# Generated by Django 4.2.20 on 2025-05-08 12:55

from django.db import migrations
import langcorrect.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_user_is_system'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', langcorrect.users.models.ActiveUserManager()),
                ('all_objects', langcorrect.users.models.AllUserManager()),
            ],
        ),
    ]
