# Generated by Django 4.2.20 on 2025-04-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='is_removed',
        ),
    ]
