# Generated by Django 4.2.20 on 2025-04-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagelevel',
            name='is_removed',
        ),
    ]
