# Generated by Django 4.2.3 on 2023-07-30 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prompt",
            options={"ordering": ["-created"]},
        ),
    ]
