# Generated by Django 4.2.9 on 2025-02-01 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_alter_prompt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
