# Generated by Django 4.2.3 on 2023-07-22 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("corrections", "0003_overallfeedback"),
        ("posts", "0002_postrow"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostReply",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("text", models.TextField()),
                ("dislike", models.BooleanField(default=False)),
                (
                    "corrected_row",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="corrections.correctedrow"
                    ),
                ),
                (
                    "perfect_row",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="corrections.perfectrow"
                    ),
                ),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posts.post")),
                (
                    "recipient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="which_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_to_comment",
                        to="posts.postreply",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
