# Generated by Django 4.2.3 on 2023-07-29 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_postreply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postreply",
            options={"ordering": ["created"]},
        ),
    ]
