# Generated by Django 4.2.7 on 2024-01-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_postimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_corrected",
            field=models.BooleanField(default=False),
        ),
    ]
