# Generated by Django 4.2.9 on 2024-07-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_language_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostReply',
        ),
    ]
