# Generated by Django 4.2.9 on 2024-07-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_delete_postreply'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created'], name='posts_post_created_26d9b3_idx'),
        ),
    ]
