# Generated by Django 4.2.3 on 2023-08-31 03:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("customer_id", models.CharField(max_length=255)),
                ("subscription_id", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "product",
                    models.CharField(
                        choices=[("monthly", "Monthly Premium"), ("yearly", "Yearly Premium")], max_length=7
                    ),
                ),
                (
                    "status",
                    models.CharField(choices=[("P", "Pending"), ("C", "Completed"), ("F", "Failed")], max_length=1),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("coupon_used", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "stripe_customer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subscriptions.stripecustomer"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
