# Generated by Django 4.2.3 on 2023-07-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_postrow"),
        ("corrections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correctedrow",
            name="post_row",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="posts.postrow"
            ),
        ),
    ]
