# Generated by Django 4.2.9 on 2024-07-05 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_alter_post_language_level'),
        ('corrections', '0003_overallfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUserCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('overall_feedback', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PostCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('correction', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('feedback_type', models.CharField(choices=[('perfect', 'Perfect'), ('corrected', 'Corrected')], max_length=10)),
                ('correction_types', models.ManyToManyField(blank=True, to='corrections.correctiontype')),
                ('post_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postrow')),
                ('user_correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrections.postusercorrection')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='corrections.postusercorrection')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddConstraint(
            model_name='postcorrection',
            constraint=models.UniqueConstraint(fields=('post_row', 'user_correction'), name='unique_post_row_user_correction'),
        ),
    ]
