# Generated by Django 4.2.9 on 2024-05-22 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_language_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corrections', '0003_overallfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRowFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('feedback_type', models.CharField(choices=[('perfect', 'Perfect'), ('corrected', 'Corrected')], max_length=10)),
                ('correction', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('correction_types', models.ManyToManyField(blank=True, to='corrections.correctiontype')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('post_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postrow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='postrowfeedback',
            constraint=models.UniqueConstraint(fields=('post_row', 'user'), name='unique_user_post_row_feedback'),
        ),
    ]
