# Generated by Django 4.2.9 on 2024-07-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0004_postusercorrection_postcorrection_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='correction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corrections.postcorrection'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='corrections.comment'),
        ),
    ]
