# Generated by Django 4.2.9 on 2024-07-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0005_comment_correction_comment_parent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postusercorrection',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post'),
        ),
    ]
