# Generated by Django 4.2.9 on 2024-07-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0006_postusercorrection_unique_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcorrection',
            name='user_correction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='corrections.postusercorrection'),
        ),
    ]
