# Generated by Django 4.2.9 on 2024-07-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_delete_postreply'),
        ('corrections', '0007_alter_postcorrection_user_correction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overallfeedback',
            name='post',
        ),
        migrations.RemoveField(
            model_name='overallfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfectrow',
            name='post',
        ),
        migrations.RemoveField(
            model_name='perfectrow',
            name='post_row',
        ),
        migrations.RemoveField(
            model_name='perfectrow',
            name='user',
        ),
        migrations.DeleteModel(
            name='CorrectedRow',
        ),
        migrations.DeleteModel(
            name='OverallFeedback',
        ),
        migrations.DeleteModel(
            name='PerfectRow',
        ),
    ]
