# Generated by Django 4.2.6 on 2023-10-26 05:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Membership",
        ),
    ]
