# Generated by Django 4.2.3 on 2023-09-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="rank",
            field=models.IntegerField(default=0),
        ),
    ]
