# Generated by Django 4.2.3 on 2023-09-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0002_contribution_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="prompt_count",
            field=models.IntegerField(default=0),
        ),
    ]
