# Generated by Django 4.2.3 on 2023-09-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0003_contribution_prompt_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="writing_streak",
            field=models.IntegerField(default=0),
        ),
    ]
