# Generated by Django 4.2.20 on 2025-04-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_alter_contribution_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='is_removed',
        ),
    ]
